services:
  - type: web
    name: real-estate-admin
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: http://localhost:4000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html